#!/usr/bin/env bash

items="app config ../../node_modules/sql-query ../../lib server.js"

watch=""
for i in $items; do
  watch="$watch --watch $i"
done

# Runs a developement server that watches for file changes.
nodemon $watch server.js
